/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\Administrator\\Desktop\\blog\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"

export default [
  m0
]