/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端小菜鸟的博客",
  "description": "专注于技术的积累",
  "base": "/blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/blogtimg.jpg",
        "heroText": "专注于前端技术的积累",
        "tagline": "记录每一天的进步，一分耕耘，一分收获",
        "actionLink": "/zh/guide/",
        "features": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b198391",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/nginx/",
      "relativePath": "src/nginx/README.md",
      "key": "v-c1a0952a",
      "path": "/src/nginx/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/ES6/",
      "relativePath": "src/ES6/README.md",
      "key": "v-47c46acf",
      "path": "/src/ES6/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/",
      "relativePath": "src/README.md",
      "key": "v-7741ab58",
      "path": "/src/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/user/",
      "relativePath": "src/user/README.md",
      "key": "v-48f28321",
      "path": "/src/user/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/vue/",
      "relativePath": "src/vue/README.md",
      "key": "v-3a7ae553",
      "path": "/src/vue/",
      "headers": [
        {
          "level": 2,
          "title": "安装node以及npm",
          "slug": "安装node以及npm"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/src/vue/index/",
      "relativePath": "src/vue/index/README.md",
      "key": "v-4528873a",
      "path": "/src/vue/index/",
      "headers": [
        {
          "level": 2,
          "title": "v-bind指令",
          "slug": "v-bind指令"
        },
        {
          "level": 2,
          "title": "v-if指令",
          "slug": "v-if指令"
        },
        {
          "level": 2,
          "title": "v-for指令",
          "slug": "v-for指令"
        },
        {
          "level": 2,
          "title": "v-on指令",
          "slug": "v-on指令"
        },
        {
          "level": 2,
          "title": "v-model指令",
          "slug": "v-model指令"
        },
        {
          "level": 2,
          "title": "v-show指令",
          "slug": "v-show指令"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/src/vue/liftCycle/",
      "relativePath": "src/vue/liftCycle/README.md",
      "key": "v-2a517f68",
      "path": "/src/vue/liftCycle/",
      "headers": [
        {
          "level": 2,
          "title": "beforeCreate",
          "slug": "beforecreate"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/src/webPack/",
      "relativePath": "src/webPack/README.md",
      "key": "v-6a784676",
      "path": "/src/webPack/"
    },
    {
      "frontmatter": {},
      "regularPath": "/src/vue/vue1/",
      "relativePath": "src/vue/vue1/README.md",
      "key": "v-1a150cee",
      "path": "/src/vue/vue1/",
      "headers": [
        {
          "level": 2,
          "title": "按照惯例首先输出一个hello world",
          "slug": "按照惯例首先输出一个hello-world"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/src/vue/props/",
      "relativePath": "src/vue/props/README.md",
      "key": "v-7ceeb104",
      "path": "/src/vue/props/",
      "headers": [
        {
          "level": 2,
          "title": "计算属性",
          "slug": "计算属性"
        },
        {
          "level": 2,
          "title": "侦听器属性",
          "slug": "侦听器属性"
        },
        {
          "level": 2,
          "title": "methods属性",
          "slug": "methods属性"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/src/react/",
      "relativePath": "src/react/README.md",
      "key": "v-7aa2d761",
      "path": "/src/react/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "vue",
        "link": "/src/vue/"
      },
      {
        "text": "react",
        "link": "/src/react/"
      },
      {
        "text": "ES6",
        "link": "/src/ES6/"
      },
      {
        "text": "webPack",
        "link": "/src/webPack/"
      },
      {
        "text": "nginx",
        "link": "/src/nginx/"
      },
      {
        "text": "关于我",
        "link": "/src/user/"
      }
    ],
    "sidebar": {
      "/src/vue/": [
        [
          "",
          "基本配置"
        ],
        [
          "/src/vue/vue1/",
          "基本使用"
        ],
        [
          "/src/vue/index/",
          "vue基本指令"
        ],
        [
          "/src/vue/props/",
          "vue常用属性"
        ],
        [
          "/src/vue/liftCycle/",
          "vue生命周期"
        ]
      ]
    }
  }
}